version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pre-commit
    versions:
    - 2.10.1
    - 2.11.0
    - 2.11.1
    - 2.12.0
  - dependency-name: sphinx
    versions:
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.5.3
  - dependency-name: twine
    versions:
    - 3.4.0
  - dependency-name: tox
    versions:
    - 3.22.0
  - dependency-name: pandas
    versions:
    - 1.2.2
    - 1.2.3
  - dependency-name: flake8
    versions:
    - 3.9.0
  - dependency-name: watchdog
    versions:
    - 2.0.0
    - 2.0.1
    - 2.0.2
